/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.proj;

import db.DbConnect;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.KeyEvent;
import java.io.IOException;
import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Mithuna
 */


public class Bill extends javax.swing.JFrame {
  String val=null;
  String itemcode=null;
  String itemname=null;
  int inx=0;
  float price,net=0;
  
    /**
     * Creates new form Login
     */
    Connection con=null;
    public Bill() {
        initComponents();
        con=DbConnect.connect();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/proj/icons8_close_window_30px_2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dineth\\Documents\\NetBeansProjects\\coop\\src\\images\\titlelogo.png")); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Item code");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, 23));

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 325, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 204));
        jLabel9.setText("Quentity");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, -1, 23));

        jSpinner1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setOpaque(false);
        jSpinner1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinner1KeyPressed(evt);
            }
        });
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 72, -1));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 102));

        jTable2.setBackground(new java.awt.Color(102, 102, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Item code", "Item name", "Unit Price", "QTY", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setOpaque(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setMinWidth(50);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setPreferredWidth(10);
            jTable2.getColumnModel().getColumn(4).setMinWidth(40);
            jTable2.getColumnModel().getColumn(4).setPreferredWidth(40);
            jTable2.getColumnModel().getColumn(4).setMaxWidth(40);
            jTable2.getColumnModel().getColumn(5).setMinWidth(120);
            jTable2.getColumnModel().getColumn(5).setPreferredWidth(120);
            jTable2.getColumnModel().getColumn(5).setMaxWidth(120);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 584, 292));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Total amount :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 88, 15));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/proj/icons8_logout_rounded_left_filled_30px.png"))); // NOI18N
        jLabel2.setText("Logout (f12)");
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel2KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 70));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/proj/icons8_bill_30px.png"))); // NOI18N
        jLabel4.setText("Billing");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 60));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dineth\\Documents\\NetBeansProjects\\coop\\src\\images\\Untitled-3-Recovered.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
 
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      ((JSpinner.NumberEditor)jSpinner1.getEditor()).getTextField().setBackground(new java.awt.Color(102,102,102));
      ((JSpinner.NumberEditor)jSpinner1.getEditor()).getTextField().setForeground(new java.awt.Color(255,255,255));
      ((JSpinner.NumberEditor)jSpinner1.getEditor()).setBorder(null);
      
      jTable2.setBackground(new java.awt.Color(102,102,102));
      jTable2.setForeground(new java.awt.Color(255,255,255));
      jTable2.getTableHeader().setOpaque(false);
      jTable2.getTableHeader().setBackground(new java.awt.Color(0,102,102));
      jTable2.getTableHeader().setForeground(new java.awt.Color(255,255,255));
      jScrollPane2.getViewport().setBackground(new java.awt.Color(102,102,102));
      jTextField1.requestFocusInWindow();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formInputMethodTextChanged

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
     
    }//GEN-LAST:event_formKeyPressed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_DELETE){
            DefaultTableModel table=(DefaultTableModel) jTable2.getModel();
            int row=jTable2.getSelectedRow();
            int rowindex=(int) table.getValueAt(row,0);
            System.out.println("row index"+rowindex);
            System.out.println("This is "+row);
            try{
                table.removeRow(row);
                int rowcount=table.getRowCount();
                System.out.println(rowcount);
                for (int i = rowindex++; i <=rowcount; i++) {
                    table.setValueAt(rowindex--,i,0);
                    inx=rowcount++;
                }

            }
            catch(Exception e){
                System.out.println(e);
            }
        }
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            if(evt.getKeyCode()==KeyEvent.VK_SPACE)
            jTextField1.requestFocusInWindow();
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_F12){
            ImageIcon ico=new ImageIcon("LOGOUT.jpg");
                
                int x=JOptionPane.showConfirmDialog(null,"Are you sure, that you want to logout","Logout Alert",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,ico);
                System.out.println(x);
                x++;
                if (x==1) {
                    this.dispose();
                    Login log=new Login();
                    log.setVisible(true);
                    
                        try {
                            con.close();
                        } catch (SQLException ex) {
                            System.out.println("Connection close error");
                        }
                }
            }
    }//GEN-LAST:event_jTable2KeyPressed

    private void jSpinner1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinner1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            System.out.println("pressed");
            int qty=(int) jSpinner1.getValue();
            String code=jTextField1.getText();
            System.out.println(qty+" "+ code);
            if (code.equals(null)){
                JOptionPane.showMessageDialog(null,"Please enter the Item code");
                jTextField1.requestFocusInWindow();
            }
            else{
                inx++;
                try {
                    System.out.println("pressed");
                    System.out.println(qty+" "+ code);
                    Statement stmt=con.createStatement();
                    String sql="select * from item,prices where item.item_code=prices.item_code and item.item_code='" + code + "' ";
                    //String sql2="select * from prices where item_code='" + code + "' ";
                    ResultSet res=stmt.executeQuery(sql);
                    // ResultSet res2=stmt.executeQuery(sql2);

                    if (res.next()==true){

                        {
                            this.itemcode=code;
                            this.itemname=res.getString("item_name").toString();
                            this.price=res.getFloat("price");

                        }

                        System.out.println(itemcode);
                        System.out.println(itemname);
                        System.out.println(price);
                        float total=price* (Integer)jSpinner1.getValue();

                        net += total;

                        jLabel8.setText("Rs. "+ String.valueOf(net)+ " /=");
                        Object row[]={inx,itemcode,itemname,price,jSpinner1.getValue(),total};
                        DefaultTableModel model=(DefaultTableModel) jTable2.getModel();
                        model.addRow(row);
                        jTextField1.setText("");
                        jSpinner1.setValue(Integer.valueOf(1));
                        jTextField1.requestFocusInWindow();
                    }
                    else
                    JOptionPane.showMessageDialog(null,"Invalid Barcode Entry");

                }

                catch (SQLException ex){
                    Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
        
        if(evt.getKeyCode()==KeyEvent.VK_F12){
                JOptionPane.showConfirmDialog(null,"Are you sure, that you want to logout","Logout Alert",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            }

    }//GEN-LAST:event_jSpinner1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            try {
                jTextField1.setText((String) Toolkit.getDefaultToolkit().getSystemClipboard().getData(DataFlavor.stringFlavor));
                jSpinner1.requestFocusInWindow();
            } catch (UnsupportedFlavorException ex) {
                Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
        if(evt.getKeyCode()==KeyEvent.VK_F12){
                ImageIcon ico=new ImageIcon("Images/icons8_logout_rounded_left_filled_15px.png");
               int input= JOptionPane.showConfirmDialog(null,"Are you sure, that you want to logout ?","Logout Alert",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,ico);
               System.out.println(input);
            }

    }//GEN-LAST:event_jTextField1KeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyPressed
            
    }//GEN-LAST:event_jLabel2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bill().setVisible(true);
            }
        });
    }
    public void logface (){
        this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}


  
